In [5]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [6]:
df = pd.read_csv(r"D:\data science csv's\file2.csv")
df


area  bedrooms  age   price
0  2600       3.0   20  234566
1  3454       2.0   13  234567
2  3456       NaN   15    7654
3   345       4.0   45    3437
4  3457       3.0    1    8743

In [7]:
import math
m = math.floor(df.bedrooms.median())
df.bedrooms = df.bedrooms.fillna(m)
df

area  bedrooms  age   price
0  2600       3.0   20  234566
1  3454       2.0   13  234567
2  3456       3.0   15    7654
3   345       4.0   45    3437
4  3457       3.0    1    8743

In [8]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [23]:
reg.coef_

array([-6.83824681e+01, -2.30197753e+05,  5.20762878e+02])

In [24]:
reg.intercept_

960657.7990114569

In [25]:
reg.predict([[4567,2,45]])

array([211393.89139263])

In [ ]:
####saving the predicted data in file

In [2]:
import pickle

In [10]:
with open ('model_pickel','wb') as f:
    pickle.dump(reg,f)

In [11]:
import os

In [12]:
pwd

'C:\\Users\\HP\\data science code'

In [14]:
with open('model_pickel','rb') as f:
    np = pickle.load(f)

In [15]:
np.predict([[4567,2,45]])

array([211393.89139263])

In [ ]:
###### joblib is more preferable for high data files to load data

In [17]:
import joblib 

In [18]:
joblib.dump(reg,'model_joblib')

['model_joblib']

In [20]:
nj = joblib.load('model_joblib')

In [21]:
nj.predict([[4567,2,45]])

array([211393.89139263])